apiVersion: v1

kind: Service

metadata:

  labels:

    service: udaconnect-consumer-service

  name: udaconnect-consumer-service

spec:

  ports:

  - name: "9093"

    port: 9093

    targetPort: 9093

    nodePort: 30004

  selector:

    service: udaconnect-consumer-service

  type: NodePort

---

apiVersion: apps/v1

kind: Deployment

metadata:

  labels:

    service: udaconnect-consumer-service

  name: udaconnect-consumer-service

spec:

  replicas: 1

  selector:

    matchLabels:

      service: udaconnect-consumer-service

  template:

    metadata:

      labels:

        service: udaconnect-consumer-service

    spec:

      containers:

      - image: richardvecsey/udaconnect-consumer:latest

        name: udaconnect-consumer-service

        imagePullPolicy: Always

        env:

        - name: DB_USERNAME

          valueFrom:

            configMapKeyRef:

              name: db-env

              key: DB_USERNAME

        - name: DB_PASSWORD

          valueFrom:

            secretKeyRef:

              name: db-secret

              key: DB_PASSWORD

        - name: DB_NAME

          valueFrom:

            configMapKeyRef:

              name: db-env

              key: DB_NAME

        - name: DB_HOST

          valueFrom:

            configMapKeyRef:

              name: db-env

              key: DB_HOST

        - name: DB_PORT

          valueFrom:

            configMapKeyRef:

              name: db-env

              key: DB_PORT

      restartPolicy: Always
