name: udaconnect - Package with Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push (consumer-service)
        uses: docker/build-push-action@v2
        with:
          context: ./modules/consumer
          file: ./modules/consumer/Dockerfile
          push: true
          tags: richardvecsey/udaconnect-consumer:latest

    - name: Build and push (frontend-app)
      uses: docker/build-push-action@v2
      with:
        context: ./modules/frontend
        file: ./modules/frontend/Dockerfile
        push: true
        tags: richardvecsey/udaconnect-app:latest

      - name: Build and push (grpc-service)
        uses: docker/build-push-action@v2
        with:
          context: ./modules/grpc
          file: ./modules/grpc/Dockerfile
          push: true
          tags: richardvecsey/udaconnect-grpc:latest

      - name: Build and push (loc-service)
        uses: docker/build-push-action@v2
        with:
          context: ./modules/loc
          file: ./modules/loc/Dockerfile
          push: true
          tags: richardvecsey/udaconnect-loc:latest

      - name: Build and push (person-connect-service)
        uses: docker/build-push-action@v2
        with:
          context: ./modules/person-connect
          file: ./modules/person-connect/Dockerfile
          push: true
          tags: richardvecsey/udaconnect-person-connect:latest
